구독자의 nextQuestionSequence값을 증가시킨다.
maeil-mail/maeil-mail-be pull request #91
Opened 2024-11-05 14:11 UTC by kunsanglee

```java
@Scheduled(cron = "0 0 7 * * MON-FRI")
    public void sendMail() {
        log.info("메일 전송을 시작합니다.");
        LocalDateTime now = ZonedDateTime.now(KOREA_ZONE).toLocalDateTime();
        List<Subscribe> subscribes = subscribeRepository.findAllByCreatedAtBefore(now);
        log.info("{}명의 사용자에게 메일을 전송합니다.", subscribes.size());

        subscribes.stream()
                .filter(it -> distributedSupport.isMine(it.getId()))
                .map(this::choiceQuestion)
                .filter(Objects::nonNull)
                .forEach(mailSender::sendMail);
    }
```
sendMail에서 발송한 메일 중 성공한 메일 이벤트만 nextQuestionSequence를 증가시키려고 했습니다.
그런데 현재 MailEvent 엔티티가 Subscribe 엔티티의 id를 가지고 있지 않아서, email, type, isSuccess로 성공한 메일 이벤트에 한해서 조회한 Subscribe 객체를 가지고 구독자의 시퀀스를 증가 시켜야 하기 때문에 매우 복잡한 상황입니다.

그래서 현재 시점에서는 발송에 실패한 메일이 있다면 재전송 처리하고 22시에 스케줄을 실행하여 nextQuestionSequence를 증가하도록 작성했습니다.

```java
// SendQuestionScheduler.class
@Transactional
@Scheduled(cron = "0 0 22 * * MON-FRI")
public void increaseNextQuestionSequence() {
    LocalDateTime baseDateTime = ZonedDateTime.of(LocalDate.now(), LocalTime.of(7, 0), KOREA_ZONE).toLocalDateTime();
    subscribeRepository.increaseNextQuestionSequence(baseDateTime);
}

// SubscribeRepository.class
@Modifying
@Query("update Subscribe s set s.nextQuestionSequence = s.nextQuestionSequence + 1 where s.createdAt < :baseDateTime")
void increaseNextQuestionSequence(LocalDateTime baseDateTime);
```
SubscribeRepository에 구독자의 시퀀스를 증가시키는 bulk update 쿼리 메서드를 작성했습니다. 그리고 이 메서드를 호출하는 SendQuestionScheduler의 메서드에 `@Transactional`을 선언하여 벌크 업데이트 쿼리를 원자적으로 실행하도록 했습니다.

2024-11-05 15:45 UTC, le2sky requested changes
이상 안녕하세요. 아톰입니다. PR 본문에 #81, #90 번 이슈 close 처리 부탁 드립니다.
중요한 PR이라고 생각하여 몇 가지 코멘트 남겨놨어요. 시간 나실 때 확인 부탁 드립니다!

2024-11-05 15:45 UTC, le2sky commented on src/main/java/maeilmail/subscribe/core/SendQuestionScheduler.java
> +    @Scheduled(cron = "0 0 7 * * MON-FRI")
Admin 스케줄러에도 Mon-FRI 설정해주시면 감사하겠습니다. 그리고, 각 스케줄에 대한 시간, 요일 검증 테스트 코드가 필요해 보입니다. 기존에 작성되어있는 스케줄러 테스트를 참고하시면 됩니다! 😀

2024-11-05 15:45 UTC, le2sky commented on src/main/java/maeilmail/subscribe/core/SubscribeRepository.java
>  }
이 부분은 사이드 이펙트가 심한 쿼리라서 테스트 코드를 작성하고, 텍스트 블록을 사용하여 가독성을 높이는 것은 어떨까요?

2024-11-06 03:18 UTC, kunsanglee commented on src/main/java/maeilmail/subscribe/core/SubscribeRepository.java
>  }
SubscribeSequenceScheduler로 시퀀스 증가하는 책임을 분리했습니다.
하지만 JpaAuditing을 사용하는 BaseEntity의 createdAt 필드를 테스트 목적으로 조작하기 힘든 상황이라 테스트를 Disabled 해놨는데 좋은 아이디어 있을까요?

2024-11-06 08:09 UTC, le2sky approved these changes
> SubscribeSequenceScheduler로 시퀀스 증가하는 책임을 분리했습니다.
하지만 JpaAuditing을 사용하는 BaseEntity의 createdAt 필드를 테스트 목적으로 조작하기 힘든 상황이라 테스트를 Disabled 해놨는데 좋은 아이디어 있을까요?

allArgs를 생성하거나, 네이티브 쿼리를 생성하거나, 아니면 생성된 created_at만 가지고 변경이 잘되는지 정도만 검증하는 식으로 타협해볼 수 있을 것 같아요. 당장 내일부터 필요한 쿼리이므로 우선 머지 시키고 테스트 코드는 빠른 시일내로 추가해놓을게요! 고생하셨습니다. 😀

2024-11-06 08:09 UTC, merged